config:
  upstream:
    kind: github
    url: "https://github.com"
    credentials:
      existingSecret: git-proxy-credentials
  auth:
    existingSecret: "git-proxy-auth"
  issueUpstream:
    enabled: true
    kind: github
    url: "https://github.com"
  repos:
    "demo/demo.git": "acme/demo.git"
  publicRepos:
    - "public/*"
